export const BASE_LAYER_IDS = [
	'satellite',
	'hybrid',
	'streets',
	'streets-v2',
	'streets-v2-dark',
	'streets-v2-light',
	'streets-v2-night',
	'streets-v2-pastel',
	'outdoor-v2',
	'outdoor-v2-dark',
	'winter-v2',
	'winter-v2-dark',
	'basic-v2',
	'basic-v2-dark',
	'basic-v2-light',
	'bright-v2',
	'bright-v2-dark',
	'bright-v2-light',
	'bright-v2-pastel',
	'topo-v2',
	'topo-v2-shiny',
	'topo-v2-pastel',
	'topo-v2-topographique',
	'voyager-v2',
	'voyager-v2-darkmatter',
	'voyager-v2-positron',
	'voyager-v2-vintage',
	'toner-v2',
	'toner-v2-background',
	'toner-v2-lite',
	'toner-v2-lines',
	'openstreetmap',
	'dataviz',
	'dataviz-dark',
	'dataviz-light',
	'backdrop',
	'backdrop-dark',
	'ocean'
] as const;

export type BaseLayerId = (typeof BASE_LAYER_IDS)[number];
